[package]
name = "rust_bits"
version = "0.1.0"
authors = ["Paul Fesenmeier <pfesenmeier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
